document.write("");
document.write("<!--header start-->");
document.write("<header class=\"header white-bg\">");
document.write("<div class=\"navbar-header white-bg\">");
document.write("<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">");
document.write("<span class=\"fa fa-bars\"></span>");
document.write("</button>");
document.write("<!--logo start-->");
document.write("<a id=\"logo_link\" href=\"../index.html\" class=\"logo\">Blue0x|<span>EXPLORER</span></a>");
document.write("<!--logo end-->");
document.write("<div class=\"horizontal-menu navbar-collapse collapse\">");
document.write("<ul class=\"nav navbar-nav\">");
document.write("<li class=\"dropdown\">");
document.write("<a href=\"../index.html\">Search Another Transaction</a>");
document.write("</li>");
document.write("</div>");
document.write("<div class=\"horizontal-menu navbar-collapse collapse\">");
document.write("</header>");
document.write("<!--header end-->");
